<?php

declare(strict_types=1);

namespace EICC\StaticForge\Features\RobotsTxt\Services;

class RobotsTxtGenerator
{
    /**
     * Generate robots.txt content
     *
     * @param array<string, array{Disallow?: array<int, string>, Allow?: array<int, string>}> $rules
     */
    public function generate(string $siteBaseUrl, array $rules): string
    {
        $content = "# robots.txt generated by StaticForge\n";
        $content .= "# " . date('Y-m-d H:i:s') . "\n\n";

        foreach ($rules as $agent => $directives) {
            $content .= "User-agent: {$agent}\n";

            $disallows = $directives['Disallow'] ?? [];
            $allows = $directives['Allow'] ?? [];

            if (empty($disallows) && empty($allows) && $agent === '*') {
                $content .= "# No disallowed paths\n";
                $content .= "Disallow:\n";
            } else {
                if (!empty($disallows)) {
                    $disallows = array_unique($disallows);
                    sort($disallows);
                    foreach ($disallows as $path) {
                        $content .= "Disallow: {$path}\n";
                    }
                }

                if (!empty($allows)) {
                    $allows = array_unique($allows);
                    sort($allows);
                    foreach ($allows as $path) {
                        $content .= "Allow: {$path}\n";
                    }
                }
            }

            $content .= "\n";
        }

        // Add sitemap reference if we have a base URL
        if (!empty($siteBaseUrl)) {
            $siteBaseUrl = rtrim($siteBaseUrl, '/');
            $content .= "# Sitemap location\n";
            $content .= "Sitemap: {$siteBaseUrl}/sitemap.xml\n";
        }

        return $content;
    }
}
