<?php

namespace EICC\StaticForge\Tests\Unit\Features\HtmlRenderer;

use EICC\StaticForge\Core\Events\RenderEvent;
use EICC\StaticForge\Features\HtmlRenderer\Feature;
use EICC\StaticForge\Core\EventManager;
use EICC\StaticForge\Core\FeatureFactory;
use EICC\Utils\Container;
use EICC\StaticForge\Tests\Unit\UnitTestCase;
use org\bovigo\vfs\vfsStream;
use org\bovigo\vfs\vfsStreamDirectory;

/**
 * @covers \EICC\StaticForge\Features\HtmlRenderer\Feature
 */
class FeatureTest extends UnitTestCase
{
    private Feature $feature;

    private EventManager $eventManager;
    private string $sourceDir;
    private string $outputDir;
    private string $templateDir;

    protected function setUp(): void
    {
        parent::setUp();

        // Create real temp directories
        $this->sourceDir = sys_get_temp_dir() . '/staticforge_source_' . uniqid();
        $this->outputDir = sys_get_temp_dir() . '/staticforge_output_' . uniqid();
        $this->templateDir = sys_get_temp_dir() . '/staticforge_templates_' . uniqid();

        mkdir($this->sourceDir, 0755, true);
        mkdir($this->outputDir, 0755, true);
        mkdir($this->templateDir . '/test', 0755, true);

        // Set up container
        // Use bootstrapped container from parent::setUp()
        $this->setContainerVariable('SOURCE_DIR', $this->sourceDir);
        $this->setContainerVariable('OUTPUT_DIR', $this->outputDir);
        $this->setContainerVariable('TEMPLATE_DIR', $this->templateDir);
        $this->setContainerVariable('TEMPLATE', 'test');
        $this->setContainerVariable('SITE_NAME', 'Test Site');
        $this->setContainerVariable('SITE_BASE_URL', 'https://example.com/');

        // Override site_config to ensure SITE_NAME is used or matches
        $this->setContainerVariable('site_config', ['site' => ['name' => 'Test Site']]);

        // Logger already registered by bootstrap

        // Set up extension registry
        $extensionRegistry = new \EICC\StaticForge\Core\ExtensionRegistry($this->container);
        $this->addToContainer(\EICC\StaticForge\Core\ExtensionRegistry::class, $extensionRegistry);

        // Set up event manager
        $this->eventManager = new EventManager();

        // Create feature
        $feature = (new FeatureFactory($this->container))->make(Feature::class);
        $this->assertInstanceOf(Feature::class, $feature);
        $this->feature = $feature;
        $this->feature->register($this->eventManager);

        // Create test templates
        $this->createTestTemplates();
    }

    /**
     * @param array<string, mixed> $metadata
     */
    private function makeEvent(string $filePath, array $metadata = []): RenderEvent
    {
        return new RenderEvent(
            name: 'RENDER',
            filePath: $filePath,
            fileUrl: '',
            metadata: $metadata,
        );
    }

    public function testRegisterAddsHtmlExtension(): void
    {
        $extensionRegistry = $this->container->get(\EICC\StaticForge\Core\ExtensionRegistry::class);
        $this->assertTrue($extensionRegistry->isRegistered('.html'));
    }

    public function testHandleRenderIgnoresNonHtmlFiles(): void
    {
        $event = $this->makeEvent('/test/file.txt');

        $this->feature->handleRender($event);

        $this->assertNull($event->renderedContent);
        $this->assertNull($event->outputPath);
    }

    public function testHandleRenderProcessesHtmlFileWithoutYaml(): void
    {
        // Create test HTML file
        $htmlContent = '<h1>Test Page</h1><p>This is test content.</p>';
        $testFile = $this->sourceDir . '/test.html';
        file_put_contents($testFile, $htmlContent);

        $event = $this->makeEvent($testFile);

        $this->feature->handleRender($event);

        // Renderer should store rendered content, not write to disk
        $this->assertNotNull($event->renderedContent);
        $this->assertNotNull($event->outputPath);
        $this->assertStringContainsString($this->outputDir . '/test.html', $event->outputPath);

        // Check rendered content contains expected elements
        $this->assertStringContainsString('<title>Untitled Page | Test Site</title>', $event->renderedContent);
        $this->assertMatchesRegularExpression('/<h1>\s*Test Page\s*<\/h1>/', $event->renderedContent);
        $this->assertStringContainsString('Generated by StaticForge', $event->renderedContent);
    }

    public function testHandleRenderProcessesHtmlFileWithYaml(): void
    {
        // Create test HTML file with INI frontmatter
        $htmlContent = <<<HTML
<!-- INI
title = "My Test Page"
description = "A test page for StaticForge"
tags = "test, example"
category = "documentation"
-->
<h1>Welcome</h1>
<p>This is the main content.</p>
HTML;

        $testFile = $this->sourceDir . '/page.html';
        file_put_contents($testFile, $htmlContent);

        $event = $this->makeEvent($testFile, [
            'title' => 'My Test Page',
            'description' => 'A test page for StaticForge',
            'tags' => 'test, example',
            'category' => 'documentation'
        ]);

        $this->feature->handleRender($event);

        $this->assertNotNull($event->renderedContent);

        // Check output file content
        $outputContent = $event->renderedContent;
        $this->assertStringContainsString('<title>My Test Page | Test Site</title>', $outputContent);
        $this->assertStringContainsString('<meta name="description" content="A test page for StaticForge">', $outputContent);
        $this->assertStringContainsString('<meta name="keywords" content="test, example">', $outputContent);
        $this->assertMatchesRegularExpression('/<h1>\s*Welcome\s*<\/h1>/', $outputContent);
        $this->assertStringNotContainsString('---', $outputContent); // YAML removed
    }

    public function testHandleRenderCreatesOutputDirectories(): void
    {
        // Create nested directory structure
        mkdir($this->sourceDir . '/blog', 0755, true);

        $htmlContent = '<h1>Blog Post</h1>';
        $testFile = $this->sourceDir . '/blog/post.html';
        file_put_contents($testFile, $htmlContent);

        $event = $this->makeEvent($testFile);

        $this->feature->handleRender($event);

        $this->assertNotNull($event->renderedContent);
        $this->assertNotNull($event->outputPath);
        // Core creates directories and writes files
        $this->assertStringContainsString('/blog/post.html', $event->outputPath);
    }

    public function testHandleRenderHandlesInvalidYaml(): void
    {
        // Create HTML file with invalid INI (note: INI format is more lenient)
        $htmlContent = <<<HTML
<!-- INI
title: Test
-->
<h1>Content</h1>
HTML;

        $testFile = $this->sourceDir . '/invalid.html';
        file_put_contents($testFile, $htmlContent);

        $event = $this->makeEvent($testFile);

        $this->feature->handleRender($event);

        $this->assertNotNull($event->renderedContent);

        // Should still process with default values
        $outputContent = $event->renderedContent;
        $this->assertStringContainsString('<title>Untitled Page | Test Site</title>', $outputContent);
        $this->assertMatchesRegularExpression('/<h1>\s*Content\s*<\/h1>/', $outputContent);
    }

    public function testHandleRenderHandlesMissingParameters(): void
    {
        $event = $this->makeEvent('');

        $this->feature->handleRender($event);

        $this->assertNull($event->renderedContent);
        $this->assertNull($event->outputPath);
    }

    public function testHandleRenderHandlesReadError(): void
    {
        $event = $this->makeEvent('/nonexistent/file.html');

        $this->feature->handleRender($event);

        $this->assertArrayHasKey('error', $event->extra);
    }

    public function testTemplateReplacementWithAllVariables(): void
    {
        // Test all template variables using the bootstrapped container
        $this->setContainerVariable('SOURCE_DIR', $this->sourceDir);
        $this->setContainerVariable('OUTPUT_DIR', $this->outputDir);
        $this->setContainerVariable('SITE_BASE_URL', 'https://mysite.com/');

        // Set site_config to ensure site_name is populated
        $this->setContainerVariable('site_config', [
            'site' => [
                'name' => 'My Amazing Site'
            ]
        ]);

        // Logger already registered by bootstrap

        // Set up extension registry
        $extensionRegistry = new \EICC\StaticForge\Core\ExtensionRegistry($this->container);
        $this->addToContainer(\EICC\StaticForge\Core\ExtensionRegistry::class, $extensionRegistry);

        // Set up event manager and register feature
        $eventManager = new EventManager();
        $feature = (new FeatureFactory($this->container))->make(Feature::class);
        $this->assertInstanceOf(Feature::class, $feature);
        $feature->register($eventManager);

        $htmlContent = <<<HTML
<!-- INI
title = "Full Test Page"
description = "Complete test with all metadata"
tags = "complete, testing, metadata"
-->
<h1>Complete Test</h1>
<p>All variables should be replaced.</p>
HTML;

        $testFile = $this->sourceDir . '/complete.html';
        file_put_contents($testFile, $htmlContent);

        $event = $this->makeEvent($testFile, [
            'title' => 'Full Test Page',
            'description' => 'Complete test with all metadata',
            'tags' => 'complete, testing, metadata'
        ]);

        $feature->handleRender($event);

        $this->assertNotNull($event->renderedContent);
        $outputContent = $event->renderedContent;

        $this->assertStringContainsString('<title>Full Test Page | My Amazing Site</title>', $outputContent);
        $this->assertStringContainsString('<meta name="description" content="Complete test with all metadata">', $outputContent);
        $this->assertStringContainsString('<meta name="keywords" content="complete, testing, metadata">', $outputContent);
        $this->assertStringContainsString('<base href="https://mysite.com/">', $outputContent);
        $this->assertMatchesRegularExpression('/<h1>\s*My Amazing Site\s*<\/h1>/', $outputContent);
        $this->assertStringContainsString('&copy; 2025 My Amazing Site', $outputContent);
    }

    protected function tearDown(): void
    {
        parent::tearDown();

        // Clean up test directories
        if (isset($this->sourceDir) && is_dir($this->sourceDir)) {
            $this->removeDirectory($this->sourceDir);
        }
        if (isset($this->outputDir) && is_dir($this->outputDir)) {
            $this->removeDirectory($this->outputDir);
        }
        if (isset($this->templateDir) && is_dir($this->templateDir)) {
            $this->removeDirectory($this->templateDir);
        }
    }

    private function createTestTemplates(): void
    {
        // Base template with meta tags support matching HtmlRenderer template vars
        $baseTemplate = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title | default("Untitled Page") }} | {{ site_name }}</title>
    {% if description %}<meta name="description" content="{{ description }}">{% endif %}
    {% if tags %}<meta name="keywords" content="{{ tags }}">{% endif %}
    {% if site_base_url %}<base href="{{ site_base_url }}">{% endif %}
</head>
<body>
    <header>
        <h1>{{ site_name }}</h1>
    </header>
    <main>
        {{ content | raw }}
    </main>
    <footer>
        <p>&copy; 2025 {{ site_name }}. Generated by StaticForge.</p>
    </footer>
</body>
</html>';
        file_put_contents($this->templateDir . '/test/base.html.twig', $baseTemplate);
    }

    // removeDirectory is now provided by UnitTestCase
}
