<?php

namespace EICC\StaticForge\Tests\Unit\Features\HtmlRenderer;

use EICC\StaticForge\Features\HtmlRenderer\Feature;
use EICC\StaticForge\Core\EventManager;
use EICC\Utils\Container;
use PHPUnit\Framework\TestCase;
use org\bovigo\vfs\vfsStream;
use org\bovigo\vfs\vfsStreamDirectory;

/**
 * @covers \EICC\StaticForge\Features\HtmlRenderer\Feature
 */
class FeatureTest extends TestCase
{
    private Feature $feature;
    private Container $container;
    private EventManager $eventManager;
    private vfsStreamDirectory $root;
    private string $sourceDir;
    private string $outputDir;

    protected function setUp(): void
    {
        parent::setUp();

        // Set up virtual filesystem
        $this->root = vfsStream::setup('test');
        $this->sourceDir = $this->root->url() . '/source';
        $this->outputDir = $this->root->url() . '/output';

        mkdir($this->sourceDir);
        mkdir($this->outputDir);

        // Set up container
        $this->container = new Container();
        $this->container->setVariable('SOURCE_DIR', $this->sourceDir);
        $this->container->setVariable('OUTPUT_DIR', $this->outputDir);
        $this->container->setVariable('SITE_NAME', 'Test Site');
        $this->container->setVariable('SITE_BASE_URL', 'https://example.com/');

        // Create a temporary log file for testing
        $logFile = sys_get_temp_dir() . '/html_renderer_test.log';
        $logger = new \EICC\Utils\Log('test', $logFile, 'INFO');
        $this->container->setVariable('logger', $logger);

        // Set up extension registry
        $extensionRegistry = new \EICC\StaticForge\Core\ExtensionRegistry($this->container);
        $this->container->add('extension_registry', $extensionRegistry);

        // Set up event manager
        $this->eventManager = new EventManager($this->container);

        // Create feature
        $this->feature = new Feature();
        $this->feature->register($this->eventManager, $this->container);
    }

    public function testRegisterAddsHtmlExtension(): void
    {
        $extensionRegistry = $this->container->get('extension_registry');
        $this->assertTrue($extensionRegistry->isRegistered('.html'));
    }

    public function testHandleRenderIgnoresNonHtmlFiles(): void
    {
        $parameters = [
            'file_path' => '/test/file.txt',
            'file_info' => []
        ];

        $result = $this->feature->handleRender($this->container, $parameters);

        $this->assertEquals($parameters, $result);
        $this->assertArrayNotHasKey('processed', $result);
    }

    public function testHandleRenderProcessesHtmlFileWithoutYaml(): void
    {
        // Create test HTML file
        $htmlContent = '<h1>Test Page</h1><p>This is test content.</p>';
        $testFile = $this->sourceDir . '/test.html';
        file_put_contents($testFile, $htmlContent);

        $parameters = [
            'file_path' => $testFile,
            'file_info' => []
        ];

        $result = $this->feature->handleRender($this->container, $parameters);

        // Renderer should store rendered content, not write to disk
        $this->assertArrayHasKey('rendered_content', $result);
        $this->assertArrayHasKey('metadata', $result);
        $this->assertArrayHasKey('output_path', $result);
        $this->assertArrayHasKey('metadata', $result);
        $this->assertStringContainsString($this->outputDir . '/test.html', $result['output_path']);

        // Check rendered content contains expected elements
        $this->assertStringContainsString('<title>Untitled Page | Test Site</title>', $result['rendered_content']);
        $this->assertStringContainsString('<h1>Test Page</h1>', $result['rendered_content']);
        $this->assertStringContainsString('Generated by StaticForge', $result['rendered_content']);
    }

    public function testHandleRenderProcessesHtmlFileWithYaml(): void
    {
        // Create test HTML file with INI frontmatter
        $htmlContent = <<<HTML
<!-- INI
title = "My Test Page"
description = "A test page for StaticForge"
tags = "test, example"
category = "documentation"
-->
<h1>Welcome</h1>
<p>This is the main content.</p>
HTML;

        $testFile = $this->sourceDir . '/page.html';
        file_put_contents($testFile, $htmlContent);

        $parameters = [
            'file_path' => $testFile,
            'file_info' => []
        ];

        $result = $this->feature->handleRender($this->container, $parameters);

        $this->assertArrayHasKey('rendered_content', $result);
        $this->assertArrayHasKey('metadata', $result);

        // Check output file content
        $outputContent = $result['rendered_content'];
        $this->assertStringContainsString('<title>My Test Page | Test Site</title>', $outputContent);
        $this->assertStringContainsString('<meta name="description" content="A test page for StaticForge">', $outputContent);
        $this->assertStringContainsString('<meta name="keywords" content="test, example">', $outputContent);
        $this->assertStringContainsString('<h1>Welcome</h1>', $outputContent);
        $this->assertStringNotContainsString('---', $outputContent); // YAML removed
    }

    public function testHandleRenderCreatesOutputDirectories(): void
    {
        // Create nested directory structure
        mkdir($this->sourceDir . '/blog', 0755, true);

        $htmlContent = '<h1>Blog Post</h1>';
        $testFile = $this->sourceDir . '/blog/post.html';
        file_put_contents($testFile, $htmlContent);

        $parameters = [
            'file_path' => $testFile,
            'file_info' => []
        ];

        $result = $this->feature->handleRender($this->container, $parameters);

        $this->assertArrayHasKey('rendered_content', $result);
        $this->assertArrayHasKey('metadata', $result);
        // Core creates directories and writes files
        $this->assertStringContainsString('/blog/post.html', $result['output_path']);
    }

    public function testHandleRenderHandlesInvalidYaml(): void
    {
        // Create HTML file with invalid INI (note: INI format is more lenient)
        $htmlContent = <<<HTML
<!-- INI
title: Test
-->
<h1>Content</h1>
HTML;

        $testFile = $this->sourceDir . '/invalid.html';
        file_put_contents($testFile, $htmlContent);

        $parameters = [
            'file_path' => $testFile,
            'file_info' => []
        ];

        $result = $this->feature->handleRender($this->container, $parameters);

        $this->assertArrayHasKey('rendered_content', $result);
        $this->assertArrayHasKey('metadata', $result);

        // Should still process with default values
        $outputContent = $result['rendered_content'];
        $this->assertStringContainsString('<title>Untitled Page | Test Site</title>', $outputContent);
        $this->assertStringContainsString('<h1>Content</h1>', $outputContent);
    }

    public function testHandleRenderHandlesMissingParameters(): void
    {
        $parameters = [];

        $result = $this->feature->handleRender($this->container, $parameters);

        $this->assertEquals($parameters, $result);
        $this->assertArrayNotHasKey('processed', $result);
    }

    public function testHandleRenderHandlesReadError(): void
    {
        $parameters = [
            'file_path' => '/nonexistent/file.html',
            'file_info' => []
        ];

        $result = $this->feature->handleRender($this->container, $parameters);

        $this->assertArrayHasKey('error', $result);
        $this->assertArrayNotHasKey('processed', $result);
    }

    public function testTemplateReplacementWithAllVariables(): void
    {
        // Test all template variables - use different container or clear existing
        $testContainer = new Container();
        $testContainer->setVariable('SOURCE_DIR', $this->sourceDir);
        $testContainer->setVariable('OUTPUT_DIR', $this->outputDir);
        $testContainer->setVariable('SITE_NAME', 'My Amazing Site');
        $testContainer->setVariable('SITE_BASE_URL', 'https://mysite.com/');

        // Create a temporary log file for testing
        $logFile = sys_get_temp_dir() . '/html_renderer_template_test.log';
        $logger = new \EICC\Utils\Log('test', $logFile, 'INFO');
        $testContainer->setVariable('logger', $logger);

        // Set up extension registry
        $extensionRegistry = new \EICC\StaticForge\Core\ExtensionRegistry($testContainer);
        $testContainer->add('extension_registry', $extensionRegistry);

        // Set up event manager and register feature
        $eventManager = new EventManager($testContainer);
        $feature = new Feature();
        $feature->register($eventManager, $testContainer);

        $htmlContent = <<<HTML
<!-- INI
title = "Full Test Page"
description = "Complete test with all metadata"
tags = "complete, testing, metadata"
-->
<h1>Complete Test</h1>
<p>All variables should be replaced.</p>
HTML;

        $testFile = $this->sourceDir . '/complete.html';
        file_put_contents($testFile, $htmlContent);

        $parameters = [
            'file_path' => $testFile,
            'file_info' => []
        ];

        $result = $feature->handleRender($testContainer, $parameters);

        $outputContent = $result['rendered_content'];

        $this->assertStringContainsString('<title>Full Test Page | My Amazing Site</title>', $outputContent);
        $this->assertStringContainsString('<meta name="description" content="Complete test with all metadata">', $outputContent);
        $this->assertStringContainsString('<meta name="keywords" content="complete, testing, metadata">', $outputContent);
        $this->assertStringContainsString('<base href="https://mysite.com/">', $outputContent);
        $this->assertStringContainsString('<h1>My Amazing Site</h1>', $outputContent);
        $this->assertStringContainsString('&copy; 2025 My Amazing Site', $outputContent);
    }
}