<?php

declare(strict_types=1);

namespace EICC\StaticForge\Tests\Unit\Features\RobotsTxt;

use EICC\StaticForge\Features\RobotsTxt\Services\RobotsTxtGenerator;
use PHPUnit\Framework\TestCase;

class RobotsTxtGeneratorTest extends TestCase
{
    private RobotsTxtGenerator $generator;

    protected function setUp(): void
    {
        $this->generator = new RobotsTxtGenerator();
    }

    public function testGenerateWithNoDisallowedPathsAddsExplicitAllowAllComment(): void
    {
        $content = $this->generator->generate('https://example.com', [
            '*' => ['Disallow' => [], 'Allow' => []],
        ]);

        $this->assertStringContainsString('User-agent: *', $content);
        $this->assertStringContainsString('# No disallowed paths', $content);
        $this->assertStringContainsString('Disallow:', $content);
    }

    public function testGenerateSortsAndDedupesDisallowedPaths(): void
    {
        $content = $this->generator->generate('https://example.com', [
            '*' => ['Disallow' => ['/zebra', '/apple', '/apple'], 'Allow' => []],
        ]);

        $this->assertMatchesRegularExpression('/Disallow: \/apple.*Disallow: \/zebra/s', $content);
        $this->assertSame(1, substr_count($content, 'Disallow: /apple'));
    }

    public function testGenerateIncludesAllowDirectives(): void
    {
        $content = $this->generator->generate('https://example.com', [
            'Bingbot' => ['Allow' => ['/']],
        ]);

        $this->assertStringContainsString('User-agent: Bingbot', $content);
        $this->assertStringContainsString('Allow: /', $content);
    }

    public function testGenerateIncludesSitemapWhenBaseUrlProvided(): void
    {
        $content = $this->generator->generate('https://example.com/', []);

        $this->assertStringContainsString('Sitemap: https://example.com/sitemap.xml', $content);
    }

    public function testGenerateOmitsSitemapWhenBaseUrlEmpty(): void
    {
        $content = $this->generator->generate('', []);

        $this->assertStringNotContainsString('Sitemap:', $content);
    }

    public function testGenerateHandlesEmptyRulesArray(): void
    {
        $content = $this->generator->generate('https://example.com', []);

        $this->assertStringContainsString('# robots.txt generated by StaticForge', $content);
        $this->assertStringNotContainsString('User-agent:', $content);
    }

    public function testGenerateWithMultipleAgentsProducesSeparateBlocks(): void
    {
        $content = $this->generator->generate('https://example.com', [
            '*' => ['Disallow' => ['/private/'], 'Allow' => []],
            'Bingbot' => ['Allow' => ['/']],
        ]);

        $this->assertStringContainsString('User-agent: *', $content);
        $this->assertStringContainsString('Disallow: /private/', $content);
        $this->assertStringContainsString('User-agent: Bingbot', $content);
        $this->assertStringContainsString('Allow: /', $content);
    }
}
