<?php

declare(strict_types=1);

namespace EICC\StaticForge\Tests\Unit\Characterization\Slug;

/**
 * One shared input corpus for the six slug implementations of design section 11.1, with the
 * output each implementation produced in 3.3.7 frozen as literals.
 *
 * ContentCreatorCommand::slugify values were captured with LC_CTYPE pinned to C.UTF-8 (see
 * SlugImplementations::pinLocale); under the "C" locale its transliteration differs.
 *
 * These are characterization values, not endorsements: several are arguably bugs (accented
 * category "Cafe" becoming "caf-cr-me", CJK categories becoming ''). They exist so the Slugger
 * migration can prove it changes nothing silently. Real category names in the "real_*" cases come
 * from staticforge/content and heartsntales.com/content.
 *
 * @phpstan-type SlugCase array{
 *     input: string,
 *     categories: string,
 *     template: string,
 *     robots: string,
 *     rss: string,
 *     fileDiscovery: string,
 *     contentCreator: string
 * }
 */
final class SlugCorpus
{
    /**
     * @return array<string, SlugCase>
     */
    public static function cases(): array
    {
        return [
        'ascii_lower' => [
            'input' => 'blog',
            'categories' => 'blog',
            'template' => 'blog',
            'robots' => 'blog',
            'rss' => 'blog',
            'fileDiscovery' => 'blog',
            'contentCreator' => 'blog',
        ],
        'mixed_case' => [
            'input' => 'My Blog Post',
            'categories' => 'my-blog-post',
            'template' => 'my-blog-post',
            'robots' => 'my-blog-post',
            'rss' => 'my-blog-post',
            'fileDiscovery' => 'my-blog-post',
            'contentCreator' => 'my-blog-post',
        ],
        'numbers' => [
            'input' => '2024 Roundup 10',
            'categories' => '2024-roundup-10',
            'template' => '2024-roundup-10',
            'robots' => '2024-roundup-10',
            'rss' => '2024-roundup-10',
            'fileDiscovery' => '2024-roundup-10',
            'contentCreator' => '2024-roundup-10',
        ],
        'digits_only' => [
            'input' => '12345',
            'categories' => '12345',
            'template' => '12345',
            'robots' => '12345',
            'rss' => '12345',
            'fileDiscovery' => '12345',
            'contentCreator' => '12345',
        ],
        'leading_trailing_spaces' => [
            'input' => '  padded  ',
            'categories' => 'padded',
            'template' => 'padded',
            'robots' => 'padded',
            'rss' => 'padded',
            'fileDiscovery' => 'padded',
            'contentCreator' => 'padded',
        ],
        'tab_separated' => [
            'input' => "a\tb",
            'categories' => 'a-b',
            'template' => 'a-b',
            'robots' => 'a-b',
            'rss' => 'a-b',
            'fileDiscovery' => 'ab',
            'contentCreator' => 'a-b',
        ],
        'newlines' => [
            'input' => "a\nb\n",
            'categories' => 'a-b',
            'template' => 'a-b',
            'robots' => 'a-b',
            'rss' => 'a-b',
            'fileDiscovery' => 'ab',
            'contentCreator' => 'a-b',
        ],
        'crlf' => [
            'input' => "a\r\nb",
            'categories' => 'a-b',
            'template' => 'a-b',
            'robots' => 'a-b',
            'rss' => 'a-b',
            'fileDiscovery' => 'ab',
            'contentCreator' => 'a-b',
        ],
        'nbsp_separator' => [
            'input' => "a\u{00A0}b",
            'categories' => 'a-b',
            'template' => 'a-b',
            'robots' => 'a-b',
            'rss' => 'a-b',
            'fileDiscovery' => 'ab',
            'contentCreator' => 'a-b',
        ],
        'repeated_hyphens' => [
            'input' => 'a---b',
            'categories' => 'a-b',
            'template' => 'a-b',
            'robots' => 'a-b',
            'rss' => 'a-b',
            'fileDiscovery' => 'a-b',
            'contentCreator' => 'a-b',
        ],
        'repeated_underscores' => [
            'input' => 'a___b',
            'categories' => 'a-b',
            'template' => 'a-b',
            'robots' => 'a-b',
            'rss' => 'a-b',
            'fileDiscovery' => 'a-b',
            'contentCreator' => 'a-b',
        ],
        'mixed_separators' => [
            'input' => 'a - _ - b',
            'categories' => 'a-b',
            'template' => 'a-b',
            'robots' => 'a-b',
            'rss' => 'a-b',
            'fileDiscovery' => 'a-b',
            'contentCreator' => 'a-b',
        ],
        'dunder' => [
            'input' => '__init__',
            'categories' => 'init',
            'template' => 'init',
            'robots' => 'init',
            'rss' => 'init',
            'fileDiscovery' => 'init',
            'contentCreator' => 'init',
        ],
        'ampersand' => [
            'input' => 'a&b',
            'categories' => 'a-b',
            'template' => 'a-b',
            'robots' => 'a-b',
            'rss' => 'a-b',
            'fileDiscovery' => 'ab',
            'contentCreator' => 'a-b',
        ],
        'qanda' => [
            'input' => 'Q&A',
            'categories' => 'q-a',
            'template' => 'q-a',
            'robots' => 'q-a',
            'rss' => 'q-a',
            'fileDiscovery' => 'qa',
            'contentCreator' => 'q-a',
        ],
        'slash' => [
            'input' => 'docs/examples',
            'categories' => 'docs-examples',
            'template' => 'docs-examples',
            'robots' => 'docs-examples',
            'rss' => 'docs-examples',
            'fileDiscovery' => 'docsexamples',
            'contentCreator' => 'docs-examples',
        ],
        'backslash' => [
            'input' => 'a\\b',
            'categories' => 'a-b',
            'template' => 'a-b',
            'robots' => 'a-b',
            'rss' => 'a-b',
            'fileDiscovery' => 'ab',
            'contentCreator' => 'a-b',
        ],
        'dot_inside' => [
            'input' => 'Dr.Who',
            'categories' => 'dr-who',
            'template' => 'dr-who',
            'robots' => 'dr-who',
            'rss' => 'dr-who',
            'fileDiscovery' => 'drwho',
            'contentCreator' => 'dr-who',
        ],
        'single_dot' => [
            'input' => '.',
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'double_dot' => [
            'input' => '..',
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'traversal' => [
            'input' => '../etc/passwd',
            'categories' => 'etc-passwd',
            'template' => 'etc-passwd',
            'robots' => 'etc-passwd',
            'rss' => 'etc-passwd',
            'fileDiscovery' => 'etcpasswd',
            'contentCreator' => 'etc-passwd',
        ],
        'encoded_dots' => [
            'input' => '%2e%2e',
            'categories' => '2e-2e',
            'template' => '2e-2e',
            'robots' => '2e-2e',
            'rss' => '2e-2e',
            'fileDiscovery' => '2e2e',
            'contentCreator' => '2e-2e',
        ],
        'accents' => [
            'input' => "Caf\u{00E9} Cr\u{00E8}me",
            'categories' => 'caf-cr-me',
            'template' => 'caf-cr-me',
            'robots' => 'caf-cr-me',
            'rss' => 'caf-cr-me',
            'fileDiscovery' => 'caf-crme',
            'contentCreator' => 'cafe-creme',
        ],
        'sharp_s' => [
            'input' => "Stra\u{00DF}e",
            'categories' => 'stra-e',
            'template' => 'stra-e',
            'robots' => 'stra-e',
            'rss' => 'stra-e',
            'fileDiscovery' => 'strae',
            'contentCreator' => 'strasse',
        ],
        'cjk' => [
            'input' => "\u{65E5}\u{672C}\u{8A9E}",
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'cjk_with_ascii' => [
            'input' => "Tokyo \u{6771}\u{4EAC} 2024",
            'categories' => 'tokyo-2024',
            'template' => 'tokyo-2024',
            'robots' => 'tokyo-2024',
            'rss' => 'tokyo-2024',
            'fileDiscovery' => 'tokyo-2024',
            'contentCreator' => 'tokyo-2024',
        ],
        'rtl_arabic' => [
            'input' => "\u{0645}\u{0631}\u{062D}\u{0628}\u{0627} "
                . "\u{0628}\u{0627}\u{0644}\u{0639}\u{0627}\u{0644}\u{0645}",
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'rtl_hebrew' => [
            'input' => "\u{05E9}\u{05DC}\u{05D5}\u{05DD}",
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'emoji_with_text' => [
            'input' => "\u{1F389} Party \u{1F389}",
            'categories' => 'party',
            'template' => 'party',
            'robots' => 'party',
            'rss' => 'party',
            'fileDiscovery' => 'party',
            'contentCreator' => 'party',
        ],
        'emoji_only' => [
            'input' => "\u{1F600}",
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'empty' => [
            'input' => '',
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'only_spaces' => [
            'input' => '   ',
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'all_symbols' => [
            'input' => '!!!',
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'symbol_mix' => [
            'input' => '@#$%^&*()',
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'only_hyphens' => [
            'input' => '---',
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'nul_inside' => [
            'input' => "a\0b",
            'categories' => 'a-b',
            'template' => 'a-b',
            'robots' => 'a-b',
            'rss' => 'a-b',
            'fileDiscovery' => 'ab',
            'contentCreator' => 'a-b',
        ],
        'nul_only' => [
            'input' => "\0",
            'categories' => '',
            'template' => '',
            'robots' => '',
            'rss' => 'category',
            'fileDiscovery' => '',
            'contentCreator' => 'untitled',
        ],
        'invalid_utf8_latin1' => [
            'input' => "caf\xE9",
            'categories' => 'caf',
            'template' => 'caf',
            'robots' => 'caf',
            'rss' => 'caf',
            'fileDiscovery' => 'caf',
            'contentCreator' => 'caf',
        ],
        'invalid_utf8_lead_bytes' => [
            'input' => "\xFF\xFEabc",
            'categories' => 'abc',
            'template' => 'abc',
            'robots' => 'abc',
            'rss' => 'abc',
            'fileDiscovery' => 'abc',
            'contentCreator' => 'abc',
        ],
        'leading_hyphen' => [
            'input' => '-leading',
            'categories' => 'leading',
            'template' => 'leading',
            'robots' => 'leading',
            'rss' => 'leading',
            'fileDiscovery' => 'leading',
            'contentCreator' => 'leading',
        ],
        'double_leading_hyphen' => [
            'input' => '--flag',
            'categories' => 'flag',
            'template' => 'flag',
            'robots' => 'flag',
            'rss' => 'flag',
            'fileDiscovery' => 'flag',
            'contentCreator' => 'flag',
        ],
        'leading_dot' => [
            'input' => '.hidden',
            'categories' => 'hidden',
            'template' => 'hidden',
            'robots' => 'hidden',
            'rss' => 'hidden',
            'fileDiscovery' => 'hidden',
            'contentCreator' => 'hidden',
        ],
        'htaccess' => [
            'input' => '.htaccess',
            'categories' => 'htaccess',
            'template' => 'htaccess',
            'robots' => 'htaccess',
            'rss' => 'htaccess',
            'fileDiscovery' => 'htaccess',
            'contentCreator' => 'htaccess',
        ],
        'trailing_dot' => [
            'input' => 'name.',
            'categories' => 'name',
            'template' => 'name',
            'robots' => 'name',
            'rss' => 'name',
            'fileDiscovery' => 'name',
            'contentCreator' => 'name',
        ],
        'apostrophe' => [
            'input' => "It's",
            'categories' => 'it-s',
            'template' => 'it-s',
            'robots' => 'it-s',
            'rss' => 'it-s',
            'fileDiscovery' => 'its',
            'contentCreator' => 'it-s',
        ],
        'cplusplus' => [
            'input' => 'C++ & C#',
            'categories' => 'c-c',
            'template' => 'c-c',
            'robots' => 'c-c',
            'rss' => 'c-c',
            'fileDiscovery' => 'c-c',
            'contentCreator' => 'c-c',
        ],
        'long_ascii' => [
            'input' => str_repeat('a', 300),
            'categories' => str_repeat('a', 300),
            'template' => str_repeat('a', 300),
            'robots' => str_repeat('a', 300),
            'rss' => str_repeat('a', 300),
            'fileDiscovery' => str_repeat('a', 300),
            'contentCreator' => str_repeat('a', 300),
        ],
        'long_words' => [
            'input' => str_repeat('word ', 100),
            'categories' => 'word' . str_repeat('-word', 99),
            'template' => 'word' . str_repeat('-word', 99),
            'robots' => 'word' . str_repeat('-word', 99),
            'rss' => 'word' . str_repeat('-word', 99),
            'fileDiscovery' => 'word' . str_repeat('-word', 99),
            'contentCreator' => 'word' . str_repeat('-word', 99),
        ],
        'real_blog' => [
            'input' => 'blog',
            'categories' => 'blog',
            'template' => 'blog',
            'robots' => 'blog',
            'rss' => 'blog',
            'fileDiscovery' => 'blog',
            'contentCreator' => 'blog',
        ],
        'real_tutorials_lower' => [
            'input' => 'tutorials',
            'categories' => 'tutorials',
            'template' => 'tutorials',
            'robots' => 'tutorials',
            'rss' => 'tutorials',
            'fileDiscovery' => 'tutorials',
            'contentCreator' => 'tutorials',
        ],
        'real_Tutorials' => [
            'input' => 'Tutorials',
            'categories' => 'tutorials',
            'template' => 'tutorials',
            'robots' => 'tutorials',
            'rss' => 'tutorials',
            'fileDiscovery' => 'tutorials',
            'contentCreator' => 'tutorials',
        ],
        'real_private' => [
            'input' => 'private',
            'categories' => 'private',
            'template' => 'private',
            'robots' => 'private',
            'rss' => 'private',
            'fileDiscovery' => 'private',
            'contentCreator' => 'private',
        ],
        'real_portfolio' => [
            'input' => 'portfolio',
            'categories' => 'portfolio',
            'template' => 'portfolio',
            'robots' => 'portfolio',
            'rss' => 'portfolio',
            'fileDiscovery' => 'portfolio',
            'contentCreator' => 'portfolio',
        ],
        'real_documentation' => [
            'input' => 'documentation',
            'categories' => 'documentation',
            'template' => 'documentation',
            'robots' => 'documentation',
            'rss' => 'documentation',
            'fileDiscovery' => 'documentation',
            'contentCreator' => 'documentation',
        ],
        'real_docs_examples' => [
            'input' => 'docs/examples',
            'categories' => 'docs-examples',
            'template' => 'docs-examples',
            'robots' => 'docs-examples',
            'rss' => 'docs-examples',
            'fileDiscovery' => 'docsexamples',
            'contentCreator' => 'docs-examples',
        ],
        'real_podcast' => [
            'input' => 'podcast',
            'categories' => 'podcast',
            'template' => 'podcast',
            'robots' => 'podcast',
            'rss' => 'podcast',
            'fileDiscovery' => 'podcast',
            'contentCreator' => 'podcast',
        ],
        'real_hearts_n_tales' => [
            'input' => 'Hearts N Tales',
            'categories' => 'hearts-n-tales',
            'template' => 'hearts-n-tales',
            'robots' => 'hearts-n-tales',
            'rss' => 'hearts-n-tales',
            'fileDiscovery' => 'hearts-n-tales',
            'contentCreator' => 'hearts-n-tales',
        ],
        ];
    }

    /**
     * Which implementations agree, per input (only inputs where they do NOT all agree).
     * Each inner list is a group of implementations producing the same output; the first group
     * always contains 'categories', the canonical implementation naming output directories.
     *
     * @return array<string, list<list<string>>>
     */
    public static function disagreements(): array
    {
        return [
            'tab_separated' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'newlines' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'crlf' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'nbsp_separator' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'ampersand' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'qanda' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'slash' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'backslash' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'dot_inside' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'single_dot' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'double_dot' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'traversal' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'encoded_dots' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'accents' => [
                ['categories', 'template', 'robots', 'rss'],
                ['fileDiscovery'],
                ['contentCreator'],
            ],
            'sharp_s' => [
                ['categories', 'template', 'robots', 'rss'],
                ['fileDiscovery'],
                ['contentCreator'],
            ],
            'cjk' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'rtl_arabic' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'rtl_hebrew' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'emoji_only' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'empty' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'only_spaces' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'all_symbols' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'symbol_mix' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'only_hyphens' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'nul_inside' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'nul_only' => [
                ['categories', 'template', 'robots', 'fileDiscovery'],
                ['rss'],
                ['contentCreator'],
            ],
            'apostrophe' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
            'real_docs_examples' => [
                ['categories', 'template', 'robots', 'rss', 'contentCreator'],
                ['fileDiscovery'],
            ],
        ];
    }
}
