<?php

declare(strict_types=1);

namespace EICC\StaticForge\Features\RobotsTxt;

class RobotsTxtGenerator
{
    /**
     * Generate robots.txt content
     * 
     * @param array<int, string> $disallowedPaths
     */
    public function generate(string $siteBaseUrl, array $disallowedPaths): string
    {
        $content = "# robots.txt generated by StaticForge\n";
        $content .= "# " . date('Y-m-d H:i:s') . "\n\n";
        $content .= "User-agent: *\n";

        if (empty($disallowedPaths)) {
            $content .= "# No disallowed paths\n";
            $content .= "Disallow:\n";
        } else {
            // Sort paths for consistent output
            $paths = $disallowedPaths;
            sort($paths);
            $paths = array_unique($paths);

            foreach ($paths as $path) {
                $content .= "Disallow: {$path}\n";
            }
        }

        // Add sitemap reference if we have a base URL
        if (!empty($siteBaseUrl)) {
            $siteBaseUrl = rtrim($siteBaseUrl, '/');
            $content .= "\n# Sitemap location\n";
            $content .= "Sitemap: {$siteBaseUrl}/sitemap.xml\n";
        }

        return $content;
    }
}
